# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.

matches:
  # Metal Song of the Day
  - trigger: ":dailymetal"
    replace: "```\r{{mydate}} Metal Song of the Day Thread\r```"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  # RC Heli  logging
  - trigger: ":rcheli"
    replace: "t add \"(T) rcheli: "

  # Exercise logging
  - trigger: ":9minkb1"
    replace: "t add \"(W) wod: 9 minute KB/BW #1 3 min ea of crawling, dead bugs, kb carry\""

  - trigger: ":9minkb2"
    replace: "t add \"(W) wod: 9 minute KB/BW #2 3 min ea of marching, crawling, kb carry\""

  - trigger: ":9minkb3"
    replace: "t add \"(W) wod: 9 minute KB/BW #3 3 min ea of dead bugs, marching, kb carry\""

  - trigger: ":tgu"
    replace: "t add \"(W) wod: turkish getups LR [20,20,20,20,20]\""

  - trigger: ":kbfs"
    replace: "t add \"(W) wod: Kettlebell Double Front Squat {x} sets of 5 @ 12kg\""

  - trigger: ":clubs"
    replace: "t add \"(W) wod: Indian Clubs 10 minutes\""

  - trigger: ":flexbar"
    replace: "t add \"(W) rehab: Flexbar \""

  - trigger: ":pball"
    replace: "t add \"(W) rehab: PowerBall \""

  - trigger: ":shieldcast"
    replace: "t add \"(W) wod: Shield Cast 10 reps 5 lbs \""

  - trigger: ":pryinghalo"
    replace: "t add \"(W) wod: Prying Squats + Halos \""

  - trigger: ":fingers"
    replace: "t add \"(W) rehab: Powerband Finger Extensions \""

  - trigger: ":deck"
    replace: "(W) wod: Rolling Deck Squats EMOM {sets} sets of 4 @ 12kg"

  - trigger: ":1club"
    replace: "(W) wod: SHC 1: {x} sets of 5 @ 3.5# [inside circles, outside circles, shield casting]"

  - trigger: ":2club"
    replace: "(W) wod: SHC 2: {x} sets of 5 @ 3.5# [inside pendulum, outside pendulum, 180 pullovers]"

  - trigger: ":3club"
    replace: "(W) wod: SHC 3: {x} sets of 5 @ 3.5# [mill, reverse mill, swipe]"
