# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.

matches:
  # Metal Song of the Day
  - trigger: ":dailymetal"
    replace: "```\r{{mydate}} Metal Song of the Day Thread\r```"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  # RC Heli  logging
  - trigger: ":rcheli"
    replace: "(T) rcheli: "

  # Exercise logging
  - trigger: ":9minkb1"
    replace: "(W) wod: 9 minute KB/BW #1 3 min ea of crawling, dead bugs, kb carry"

  - trigger: ":9minkb2"
    replace: "(W) wod: 9 minute KB/BW #2 3 min ea of marching, crawling, kb carry"

  - trigger: ":9minkb3"
    replace: "(W) wod: 9 minute KB/BW #3 3 min ea of dead bugs, marching, kb carry"

  - trigger: ":tgu"
    replace: "(W) wod: turkish getups LR [20,20,20,20,20]"

  - trigger: ":kbfs"
    replace: "(W) wod: Kettlebell Double Front Squat {x} sets of 5 @ 15kg"

  - trigger: ":clubs"
    replace: "(W) wod: Indian Clubs 10 minutes"

  - trigger: ":flexbar"
    replace: "(W) rehab: Flexbar "

  - trigger: ":pball"
    replace: "(W) rehab: PowerBall "

  - trigger: ":shieldcast"
    replace: "(W) wod: Shield Cast 10 reps 5 lbs "

  - trigger: ":pryinghalo"
    replace: "(W) wod: Prying Squats + Halos "

  - trigger: ":fingers"
    replace: "(W) rehab: Powerband Finger Extensions "

  - trigger: ":deck"
    replace: "(W) wod: Rolling Deck Squats EMOM {sets} sets of 4 @ 12kg"

  - trigger: ":1club"
    replace: "(W) wod: SHC 1: {x} sets of 5 @ 1# [inside circles, outside circles, shield casting]"

  - trigger: ":2club"
    replace: "(W) wod: SHC 2: {x} sets of 5 @ 1# [inside pendulum, outside pendulum, 180 pullovers]"

  - trigger: ":3club"
    replace: "(W) wod: SHC 3: {x} sets of 5 @ 1# [mill, reverse mill, swipe]"

  - trigger: ":sp1"
    replace: "(W) wod: SHC SP1 [inside circles, outside circles, shield casts] {x} x 5/5 @ 5#"

  - trigger: ":sp2"
    replace: "(W) wod: SHC SP2 [inside pendulum, outside pendulum, pullover] {x} x 5/5 @ 5#"

  - trigger: ":sp3"
    replace: "(W) wod: SHC SP3 [alt circles, alt pendulum, alt 180 pullover] {x} x 5/5 @ 5#"

  - trigger: ":sp4"
    replace: "(W) wod: SHC SP4 [mill, reverse mill] {x} x 5/5 @ 5#"
