timeout = 80
timeout_incomplete = 500
prevent_wake = 1
secret = "mSNFi3mQyuTPN7h+78vIAg"
# logfile = "/Users/will.killian/.talon/draconity.log"

[[pipe]]
path = "/Users/will.killian/.talon/.sys/draconity.sock"

# [[socket]]
# host = "127.0.0.1"
# port = 38065

# [[remote]]
# host = "127.0.0.1"
# port = 38065
